package by.kirill.pympproject.controller;

public enum CommandName {
    GO_TO_REGISTRATION,
    GO_TO_AUTHORIZATION,
    UNKNOWN_COMMAND,
    LOCAL,
    REGISTRATION_NEW_USER,
    VALIDATION,
    GO_TO_NEWS,
    USER_S_ACCOUNT,
    PROFILE_EDIT,
    GO_TO_EDIT_PROFILE,
    GO_TO_EDIT_NEWS,
    CREATE_NEWS,
    GO_TO_WELCOME,
    READ_NEWS,
    GO_TO_UPDATE_NEWS,
    UPDATE_NEWS,
    CREATE_COMMENT
}
